const mongoose = require('mongoose');
require('dotenv').config();
const Product = require('./models/Product');

mongoose.connect(process.env.MONGO_URI, { dbName: "menzu" }).then(async () => {
    const res1 = await Product.deleteMany({ description: /Premium grade material/ });
    const res2 = await Product.deleteMany({ 
      title: { $in: [
        "Obsidian Heavy Hoodie", 
        "Washed Graphic Tee", 
        "Ecru Essential T-Shirt", 
        "Crimson Box-Fit Hoodie", 
        "Oversized Utility Parka", 
        "Raw Selvedge Denim"
      ]}
    });
    console.log(`Deleted ${res1.deletedCount + res2.deletedCount} items generated by seed scripts.`);
    process.exit(0);
}).catch(err => {
    console.error(err);
    process.exit(1);
});
